Added test to set a user to inactive and to search users

diff --git a/src/hpc-server/hpc-ws-rs-test/src/test/dice/utils/functions b/src/hpc-server/hpc-ws-rs-test/src/test/dice/utils/functions
--- a/src/hpc-server/hpc-ws-rs-test/src/test/dice/utils/functions
+++ b/src/hpc-server/hpc-ws-rs-test/src/test/dice/utils/functions
@@ -689,6 +689,78 @@ function update_existing_user {
 }
 
 
+#Search users 
+#Inputs:     
+#       [-u userID]
+#       [-f firstName]
+#       [-l lastName]
+#       [-a] search all users, default is active only
+function search_users {
+
+    usage="USAGE: search_users -u [userid] -f [first-name] -l [last-name] -a"
+
+    OPTIND=1
+    search_args=
+
+    #By default, search the active users only
+    subset=active
+    while getopts ":u:f:l:a" opt; do
+        case $opt in
+        a)
+            subset=all
+            ;;
+        u)
+            if [ -z "$search_args" ]
+            then
+                search_args="?nciUserId=$OPTARG" 
+            else    
+                search_args=${search_args}\&nciUserId=$OPTARG 
+            fi 
+            #search_args="$search_args --data \"nciUserId=$OPTARG\"" 
+            ;;
+        f)
+            if [ -z "$search_args" ]
+            then
+                search_args="?firstName=$OPTARG" 
+            else    
+                search_args=${search_args}\&firstName=$OPTARG 
+            fi 
+            #search_args="$search_args --data \"firstName=$OPTARG\"" 
+            ;;
+        l)
+            if [ -z "$search_args" ]
+            then
+                search_args="?lastName=$OPTARG" 
+            else    
+                search_args=${search_args}\&lastName=$OPTARG 
+            fi 
+            #search_args="$search_args --data \"lastName=$OPTARG\"" 
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            echo $USAGE >&2
+            exit 1
+            ;;
+        :)
+            echo "Option -$OPTARG requires an argument." >&2
+            echo $USAGE >&2
+            exit 1
+            ;;
+        esac
+    done
+
+    response_hdr="search-$subset-users-response-header.tmp"
+    response_msg="search-$subset-users-response-message.json.tmp"
+    config=$(get_curl_config) 
+    SERVER=`cat $HPC_DM_TEST/utils/server`
+   
+    curl  -X GET ${SERVER}/user/$subset/$search_args  $config -H "Accept: application/json" -D $response_hdr -o $response_msg -s 2> curl-status
+    check_connection $response_hdr
+}
+
+
+
+
 
 
 #Update an existing  group
