Added dice tests for move/rename capability

diff --git a/src/hpc-server/hpc-ws-rs-test/src/test/dice/utils/functions b/src/hpc-server/hpc-ws-rs-test/src/test/dice/utils/functions
--- a/src/hpc-server/hpc-ws-rs-test/src/test/dice/utils/functions
+++ b/src/hpc-server/hpc-ws-rs-test/src/test/dice/utils/functions
@@ -2771,6 +2771,46 @@ function register_globus_directory {
 }
 
 
+
+#Move collection or dataObject
+#Inputs 
+
+function move {
+
+    usage="USAGE: move <move-template.json> <response-header> <response-message>"
+
+    nargs=$#
+    if [ "$nargs" -ne  "3" ]
+    then
+        echo "ERROR: using move" >&2
+        echo "received $nargs arguments." >&2
+        echo "$usage" >&2
+        exit
+    fi
+
+    MOVES="$1"
+    RESPONSE_HEADER="$2"
+    RESPONSE_MSG="$3"
+
+
+    if [ ! -e $MOVE ]
+    then
+        echo "ERROR: The move template file:$MOVE does not exist "
+        exit
+    fi
+
+
+    SERVER=`cat $HPC_DM_TEST/utils/server`
+    CONFIG="$(get_curl_config)"
+    local CURL_FLAGS="-X POST ${SERVER}/move  $CONFIG  -D $RESPONSE_HEADER -o $RESPONSE_MSG "
+
+    curl -H "Content-Type: application/json" -d @$MOVES $CURL_FLAGS 2>curl-status
+
+    check_connection $RESPONSE_HEADER
+}
+
+
+
 #Check if a file contains a string 
 #inputs:
 #     <filename>
