Refactored globus download and added multiple file download

diff --git a/src/hpc-server/hpc-ws-rs-test/src/test/dice/utils/functions b/src/hpc-server/hpc-ws-rs-test/src/test/dice/utils/functions
--- a/src/hpc-server/hpc-ws-rs-test/src/test/dice/utils/functions
+++ b/src/hpc-server/hpc-ws-rs-test/src/test/dice/utils/functions
@@ -491,7 +491,8 @@ function curl_register {
 }
 
 #Substitute the "dxtestuid" string  with the actual username
-# and globus-shared-endpoint-uid with the value mentiond in $HPC_DM_TEST/utils/test-configuration  
+# and globus-shared-endpoint-uid with the value in $HPC_DM_TEST/utils/test-configuration  
+# and dXBASEFOLDER with the value in $HPC_DM_TEST/utils/test-configuration  
 #Inputs: input_file  output_file
 function update_uid {
 
@@ -505,26 +506,49 @@ function update_uid {
     OUTPUT_FILE="$2"
     USERID=`get_username $HPC_DM_TEST/utils/config` 
     ENDPOINT=$(get_json_value $HPC_DM_TEST/utils/test-configuration globus-shared-endpoint-uid)
+    BASE_PATH=$(get_basefolder)
     OUT=`cat "$INPUT_FILE" | sed "s/dxtestuid/$USERID/"`
     OUT=`echo "$OUT" | sed "s/globus-shared-endpoint-uid/$ENDPOINT/"`
+    OUT=`echo "$OUT" | sed "s/DXBASEFOLDER/$BASE_PATH/"`
     echo "$OUT" > $OUTPUT_FILE
 }
 
 
 #Verify the existance of a file in a given Globus endpoint 
+#Inputs: [-s SLEEP time
+#         -e directory listing exists, do not check globus again]
 #Inputs: <file path on the endpoint>
 #Inputs: [EndpointID]
 function verify_globus_file {
 
+    usage="${FUNCNAME} [-s sleep-time] file_path [EndpointID]"
+    local OPTIND
+    sleep_time=60
+    list_exists=false
+    while getopts ":s:e" option
+    do
+      case "${option}" in 
+        s)
+          sleep_time="${OPTARG}"
+          ;;
+        e)
+          list_exists=true
+          ;;
+        *)
+          echo "ERROR: Unsoported option ${option}" >&2
+          echo "$usage" >&2
+          exit 1
+          ;;
+      esac
+    done
+
+    shift $(( OPTIND-1 ))
     if [ "$#" -ne  1 ]  && [ "$#" -ne 2  ]
     then
-        echo "ERROR: using verify_globus_file $#"
-        echo "USAGE: verify_globus_file <file-path-on-nihnci#NIH-NCI-TRANSFER1> [globus-endpointID]  "
+        echo "ERROR: using verify_globus_file $#" >&2
+        echo "$usage" >&2
         exit
     fi
-
-    #This verifies that globus CLI is present
-    which globus > /dev/null || fail_and_exit "ERROR:No globus CLI, READ $HPC_DM_TEST/README.txt" 
 
     #If endpoint is not passed, use the default endpoint
     if [ "$#" -eq 1 ] 
@@ -536,16 +560,25 @@ function verify_globus_file {
         ENDPOINT_ID="$2"
     fi
 
-    #List the files in the path
-    PARENT_DIR=$(dirname "$FILE_PATH") 
+    ls_file=directory-list.tmp
+    if [ $list_exists == "false" ]
+    then 
 
-    #Sleep a bit for Globus to be updated
-    sleep 60  
+        #This verifies that globus CLI is present
+        which globus > /dev/null || fail_and_exit "ERROR:No globus CLI, READ $HPC_DM_TEST/README.txt" 
+ 
 
-    globus ls "$ENDPOINT_ID:$PARENT_DIR" > directory-list.tmp
+        #List the files in the path
+        PARENT_DIR=$(dirname "$FILE_PATH") 
+    
+        #Sleep a bit for Globus to be updated
+        sleep $sleep_time 
+    
+        globus ls "$ENDPOINT_ID:$PARENT_DIR" > $ls_file
+    fi
 
     FILE_NAME=$(basename $FILE_PATH)
-    EXISTS=$(grep  "$FILE_NAME" directory-list.tmp)
+    EXISTS=$(grep  "$FILE_NAME" $ls_file)
     if [ -z "$EXISTS" ]
     then
         echo "ERROR: Can not find the file $FILE_PATH in the Globus endpoint $ENDPOINT_ID"
@@ -1088,7 +1121,7 @@ function download_dataobject_sync {
     OBJECT_PATH="$1"
     SERVER=`cat $HPC_DM_TEST/utils/server`
     TEMPLATE="$HPC_DM_TEST/utils/templates/download-sync-template.json"
-    curl -H "Content-Type: application/json" -d @$TEMPLATE -X POST ${SERVER}/dataObject/$OBJECT_PATH/download  --config $HPC_DM_TEST/utils/config  -H "Accept: application/json" -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 
+    curl -H "Content-Type: application/json" -d @$TEMPLATE -X POST ${SERVER}/dataObject/$OBJECT_PATH/download  $(get_curl_config)  -H "Accept: application/json" -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 
     check_connection $RESPONSE_HEADER
 
 }
@@ -1100,7 +1133,7 @@ function download_dataobject_sync {
 #Input: [download-template]
 function download_async {
 
-    if [ -z "$1" ] 
+    if [ "$#" -lt 1 ]
     then
         echo "ERROR: using download_async"
         echo "USAGE: download_async <item-path> [download-template]"
@@ -1121,6 +1154,13 @@ function download_async {
     ITEM_PATH="$1"
     SERVER=`cat $HPC_DM_TEST/utils/server`
 
+    if [ "$ITEM_PATH" != ""  ]
+    then
+      ITEM_NAME=$(basename ${ITEM_PATH})
+      ITEM_PATH=/${ITEM_PATH}
+    else
+      ITEM_NAME=""
+    fi
    
     if [ -z "$2" ]
     then 
@@ -1129,23 +1169,18 @@ function download_async {
         TEMPLATE="$2"
     fi
 
-
-    ITEM_NAME=$(basename $ITEM_PATH)
-    TEMP=input-temp.json.tmp
-
-    
+    TEMP=download-input-temp.json.tmp
     #Update the globus endpoint
     update_uid "$TEMPLATE" "$TEMP"
 
     #Update the file name 
-    INPUT_JSON=$(cat "$TEMP" | sed "s/dxfilename/$ITEM_NAME/")
+    INPUT_JSON=$(cat "$TEMP" | sed "s@dxfilename@$ITEM_NAME@")
     echo "$INPUT_JSON" > input.json.tmp
 
-
-    curl -H "Content-Type: application/json" -d @input.json.tmp -X POST ${SERVER}/$ITEM_PATH/download  --config $HPC_DM_TEST/utils/config  -H "Accept: application/json" -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 
+    curl -H "Content-Type: application/json" -d @input.json.tmp -X POST ${SERVER}${ITEM_PATH}/download  --config $HPC_DM_TEST/utils/config  -H "Accept: application/json" -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 
     check_connection $RESPONSE_HEADER
-
 }
+
 
 
 #Get the status of asynchronousl download request 
@@ -1154,7 +1189,7 @@ function download_async {
 function get_download_status {
 
     usage="USAGE: get_download_status <taskId> <type>"
-    if [ -z "$1" ]  || [ -z "$2" ]
+    if [ "$#" -ne 2 ]
     then
         echo "ERROR: using get_download_status"
         echo "Received: $*" >&2
@@ -1167,18 +1202,24 @@ function get_download_status {
 
     taskId="$1"
     request_type="$2"
+
+    if [ "$request_type" != "" ]
+    then
+      request_type=/${request_type}
+    fi
+
     
     #Verify that taskId is a numerical value
-    re='^[0-9]+$'
-    if ! [[ "$taskId" =~ $re ]] ; then
-        echo "ERROR: taskId $taskId is not a number" >&2; 
-        exit 1
-    fi
+    #re='^[0-9]+$'
+    #if ! [[ "$taskId" =~ $re ]] ; then
+    #    echo "ERROR: taskId $taskId is not a number" >&2; 
+    #    exit 1
+    #fi
 
     SERVER=`cat $HPC_DM_TEST/utils/server`
 
     
-    curl -G -X GET ${SERVER}/$request_type/download?taskId="$taskId"  --config $HPC_DM_TEST/utils/config  -H "Accept: application/json" -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 
+    curl -G -X GET ${SERVER}${request_type}/download?taskId="$taskId"  --config $HPC_DM_TEST/utils/config  -H "Accept: application/json" -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 
     check_connection $RESPONSE_HEADER
 }
 
@@ -2272,3 +2313,58 @@ function convert_date_to_seconds  {
     date --date="$new_string" +%s
 }
 
+#Verifies the download went through and the receipt was correctly generated. 
+#Inputs: taskId: The download receipt.
+#Inputs: files_paths: The download path on Globus
+#Input: type: dataObject, collection, or ""
+function verify_globus_download {
+
+
+  taskID="$1"
+  files_paths="$2"
+  download_type="$3"
+
+  #Get the status of the download request and verify it is true
+  RESPONSE_HEADER=get-download-status-response-header.tmp
+  RESPONSE_MSG=get-download-status-response-message.json.tmp
+  get_download_status "$taskId" "$download_type" 
+  HTTP_CODE=`get_http_code $RESPONSE_HEADER`
+  echo "get_status_code $HTTP_CODE"
+
+  #Do not check the file is the code is not 200
+  if [ $HTTP_CODE != 200 ] 
+  then
+    echo "$FUNCNAME: Unable to get download status" >&2
+    exit 1
+  fi
+
+  #Verify that the download is marked complete on the download status
+  status=$(get_json_unquotted_value $RESPONSE_MSG inProgress)
+  echo "in_progress:$status"
+  mv $RESPONSE_HEADER first-get-status-header.tmp
+  mv $RESPONSE_MSG first-get-status-message.tmp
+
+
+  first=false
+  for globus_path in $files_paths
+  do
+    if [ "$first" == "false" ]
+    then
+      verify_globus_file  -s 90 $globus_path 
+      first=true
+    else
+      verify_globus_file  -e $globus_path 
+    fi 
+  done 
+
+
+  #Sleep 50s and verify the status is updated
+  sleep 50
+  RESPONSE_HEADER=get-download-status-response-header.tmp
+  RESPONSE_MSG=get-download-status-response-message.json.tmp
+  get_download_status "$taskId" "$download_type"
+
+  #Verify that the download is marked complete on the download status
+  status=$(get_json_unquotted_value $RESPONSE_MSG inProgress)
+  echo "in_progress:$status"
+}
