use a common function to check attribute existance
SVN-Revision: 973

diff --git a/src/hpc/hpc-server/hpc-ws-rs-api/test/test-register/utils/registration-functions b/src/hpc/hpc-server/hpc-ws-rs-api/test/test-register/utils/registration-functions
--- a/src/hpc/hpc-server/hpc-ws-rs-api/test/test-register/utils/registration-functions
+++ b/src/hpc/hpc-server/hpc-ws-rs-api/test/test-register/utils/registration-functions
@@ -152,3 +152,27 @@ function validate_collection {
     echo $CHECK
 }
 
+
+#Make sure the attribute exists in the response header
+function check_attribute {
+    RETURNED_MSG=$1
+    ATTRIBUTE=$2
+
+    RESPONSE_GROUPS=`cat $RETURNED_MSG | tr "{" "\n"`
+    OBJECT_GROUPS=`echo "$RESPONSE_GROUPS" | grep "$ATTRIBUTE"`
+    if [ -z "$OBJECT_GROUPS"  ]
+    then 
+        echo "ERROR: No $ATTRIBUTE is returned" 1>&2
+        exit
+    fi
+
+    VALUE=`get_json_value "$OBJECT_GROUPS" "value"`
+    if [ -z "$VALUE" ]
+    then
+        echo "ERROR: No $ATTRIBUTE is returned" 1>&2
+    exit
+    fi
+}
+
+
+
