HPCDATAMGM-1007: Display error msg on failure, delete header and msg if not requested

diff --git a/utils/scripts/functions b/utils/scripts/functions
--- a/utils/scripts/functions
+++ b/utils/scripts/functions
@@ -1454,7 +1454,7 @@ function dm_get_download_status {
 #Inputs:  <description.json>: The metadata json file
 function dm_rename() {
 
-    local USAGE="USAGE: dm_rename <description.json>"
+    local USAGE="USAGE: dm_rename <description.json> [REST-response]"
 
     if [ -z "$1" ]
     then
@@ -1485,6 +1485,23 @@ function dm_rename() {
     curl -H "Content-Type: application/json" -d @$DESCRIPTION $CURL_FLAGS  2>$HPC_DM_UTILS/temp/curl-status
 
     check_connection $RESPONSE_HEADER
+    local response_code=$(get_http_code $RESPONSE_HEADER)
+    if [ "$response_code" -ne 200 ] && [ "$response_code" -ne 201 ]
+    then
+      echo "ERROR performing rename operation " >&2
+      print_error_message "$RESPONSE_MSG" "$response_code"
+      exit 1
+    else
+
+      #Check if the user needs the response header file
+      if [ -z "$2" ]
+      then
+        rm -f "$RESPONSE_HEADER" 2> /dev/null
+      fi
+
+      rm -f "$RESPONSE_MSG" 2 > /dev/null
+    fi 
+
 
 }
 
