Added support for list of files bulk registration

diff --git a/utils/scripts/utilities b/utils/scripts/utilities
--- a/utils/scripts/utilities
+++ b/utils/scripts/utilities
@@ -583,4 +583,28 @@ function get_type  {
     fi
 }
 
+#Convert the path in the correct format depending on the os
+#Argument: <path>
+#Returns: Converted-path
+function convert_path {
 
+  if [ -z "$1" ]
+  then
+    echo "ERROR: $FUNCNAME should accept one argument." >&2
+    exit 1
+  fi
+
+  input_path="$1"
+  case "$(uname -s)" in
+    Darwin|Linux)
+      echo $input_path
+    ;;
+    CYGWIN*|MINGW32*|MSYS*)
+      echo $(cygpath -m $input_path)
+    ;;
+    *)
+      echo 'Current OS not supported' 
+      exit 1
+    ;;
+  esac
+}
