added the base-folder to the configuration file
SVN-Revision: 1946

diff --git a/src/hpc/hpc-server/hpc-ws-rs-api/test/utils/functions b/src/hpc/hpc-server/hpc-ws-rs-api/test/utils/functions
--- a/src/hpc/hpc-server/hpc-ws-rs-api/test/utils/functions
+++ b/src/hpc/hpc-server/hpc-ws-rs-api/test/utils/functions
@@ -283,19 +283,28 @@ function get_username {
 #Get the basefolder 
 function get_basefolder {
 
-    BASE_FILE="$HPC_DM_TEST/utils/base-folder"
-    if [ ! -e "$BASE_FILE" ]
-    then
-        echo "ERROR: can not find the base-folder file $BASE_FILE" 1>&2
-        exit
-    fi
+#    BASE_FILE="$HPC_DM_TEST/utils/base-folder"
+#    if [ ! -e "$BASE_FILE" ]
+#    then
+#        echo "ERROR: can not find the base-folder file $BASE_FILE" 1>&2
+#        exit
+#    fi
+#
+#    BASE_FOLDER=$(cat $BASE_FILE)
+#    if [ -z "$BASE_FOLDER" ]
+#    then
+#        echo "ERROR: the base-folder file $BASE_FILE is empyt" >&2
+#        exit
+#    fi
 
-    BASE_FOLDER=$(cat $BASE_FILE)
+    BASE_FOLDER=$(get_json_value $HPC_DM_TEST/utils/test-configuration base-folder)
+
     if [ -z "$BASE_FOLDER" ]
-    then
-        echo "ERROR: the base-folder file $BASE_FILE is empyt" >&2
-        exit
+    then 
+        echo "ERROR: Can not retrieve base-folder from $HPC_DM_TEST/utils/test-configuration "
+        exit 
     fi
+ 
 
     echo $BASE_FOLDER
 
