Added tests to saved query functions
SVN-Revision: 2040

diff --git a/src/hpc/hpc-server/hpc-ws-rs-api/test/utils/functions b/src/hpc/hpc-server/hpc-ws-rs-api/test/utils/functions
--- a/src/hpc/hpc-server/hpc-ws-rs-api/test/utils/functions
+++ b/src/hpc/hpc-server/hpc-ws-rs-api/test/utils/functions
@@ -1253,9 +1253,10 @@ function update_single_permission {
 #Register a query
 #Inputs:    <query-name> 
 #           <query-file>
+#           [PUT-POST] Either register or update
 function register_query {
 
-    USAGE="ERROR: using register_query.\nUSAGE: register_query <query-name> <query-file>"
+    USAGE="ERROR: using register_query.\nUSAGE: register_query <query-name> <query-file> [PUT-POST]"
 
     if [ -z "$1" ]
     then    
@@ -1273,6 +1274,28 @@ function register_query {
         exit
     fi
 
+    if [ -z "$3" ]
+    then
+        METHOD=PUT
+    else
+        METHOD=$3
+    fi
+
+    if [ "$METHOD" != PUT ] && [ "$METHOD" != POST ] 
+    then
+        echo "ERROR:unsupported method $METHOD" >&2
+    fi
+
+
+    if [ "$METHOD" = PUT ] 
+    then
+        RESPONSE_HEADER=register-query-response-header.tmp
+        RESPONSE_MSG=register-query-response-message.json.tmp
+    else
+        RESPONSE_HEADER=update-query-response-header.tmp
+        RESPONSE_MSG=update-query-response-message.json.tmp
+    fi
+    
     QUERY_NAME="$1"
     QUERY_PATH="$2"
 
@@ -1286,12 +1309,38 @@ function register_query {
     CONFIG="" 
     SERVER=`cat $HPC_DM_TEST/utils/server`
 
-    RESPONSE_HEADER=register-query-response-header.tmp
-    RESPONSE_MSG=register-query-response-message.json.tmp
 
-    curl -X PUT ${SERVER}/query/"$QUERY_NAME" -H "Content-Type: application/json" -d @$QUERY_PATH --config $HPC_DM_TEST/utils/config -H "Accept: application/json" -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status
+    curl -X $METHOD ${SERVER}/query/"$QUERY_NAME" -H "Content-Type: application/json" -d @$QUERY_PATH --config $HPC_DM_TEST/utils/config -H "Accept: application/json" -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status
     check_connection $RESPONSE_HEADER
 }
+
+
+#Delete a query
+#Inputs:    <query-name> 
+function delete_query {
+
+    USAGE="ERROR: using delete_query.\nUSAGE: delete_query <query-name> "
+
+    if [ -z "$1" ]
+    then    
+        echo "Missing query-name" >&2
+        echo "$USAGE"  1>&2
+        exit
+
+    fi
+
+    QUERY_NAME="$1"
+
+    SERVER=`cat $HPC_DM_TEST/utils/server`
+
+    RESPONSE_HEADER=delete-query-response-header.tmp
+    RESPONSE_MSG=delete-query-response-message.json.tmp
+
+    curl -X DELETE ${SERVER}/query/"$QUERY_NAME" --config $HPC_DM_TEST/utils/config -H "Accept: application/json" -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status
+    check_connection $RESPONSE_HEADER
+}
+
+
 
 
 #Retrieve a saved query
