Added required numerial attributes
SVN-Revision: 1783

diff --git a/src/hpc/hpc-server/hpc-ws-rs-api/test/utils/functions b/src/hpc/hpc-server/hpc-ws-rs-api/test/utils/functions
--- a/src/hpc/hpc-server/hpc-ws-rs-api/test/utils/functions
+++ b/src/hpc/hpc-server/hpc-ws-rs-api/test/utils/functions
@@ -280,6 +280,31 @@ function get_username {
 }
 
 
+#Get the basefolder 
+function get_basefolder {
+
+    BASE_FILE="$HPC_DM_TEST/utils/base-folder"
+    if [ ! -e "$BASE_FILE" ]
+    then
+        echo "ERROR: can not find the base-folder file $BASE_FILE" 1>&2
+        exit
+    fi
+
+    BASE_FOLDER=$(cat $BASE_FILE)
+    if [ -z "$BASE_FOLDER" ]
+    then
+        echo "ERROR: the base-folder file $BASE_FILE is empyt" >&2
+        exit
+    fi
+
+    echo $BASE_FOLDER
+
+}
+
+
+
+
+
 #Get a parameter from the test-configuration file
 #Usage get_parameter <parameter_name> 
 function get_parameter {
@@ -1035,5 +1060,3 @@ function get_item {
     curl -G -X GET "$SERVER/$TOTAL_PATH"  --config $HPC_DM_TEST/utils/config   -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 
     check_connection $RESPONSE_HEADER
 }
-
-
