Added the download collection funtion as part of download async
SVN-Revision: 2061

diff --git a/src/hpc/hpc-server/hpc-ws-rs-api/test/utils/functions b/src/hpc/hpc-server/hpc-ws-rs-api/test/utils/functions
--- a/src/hpc/hpc-server/hpc-ws-rs-api/test/utils/functions
+++ b/src/hpc/hpc-server/hpc-ws-rs-api/test/utils/functions
@@ -791,29 +791,29 @@ function download_dataobject_sync {
 
 
 
-#Download a dataObject asynchronously to the default globus endpoint
-#Input: <dataObject-path>
+#Download a dataObject or a collection asynchronously to the default globus endpoint
+#Input: <item-path> 
 #Input: [download-template]
-function download_dataobject_async {
+function download_async {
 
     if [ -z "$1" ] 
     then
-        echo "ERROR: using download_dataobject_sync"
-        echo "USAGE: download_dataobject_sync <dataOjbect-path>"
+        echo "ERROR: using download_async"
+        echo "USAGE: download_async <item-path> [download-template]"
         exit
     fi
 
     if [ -z $RESPONSE_HEADER ] 
     then
-        RESPONSE_HEADER=download-dataobject-response-header.tmp
+        RESPONSE_HEADER=download-response-header.tmp
     fi
 
     if [ -z $RESPONSE_MSG ] 
     then
-        RESPONSE_MSG=download-dataobject-response-message.json.tmp
+        RESPONSE_MSG=download-response-message.json.tmp
     fi
 
-    OBJECT_PATH="$1"
+    ITEM_PATH="$1"
     SERVER=`cat $HPC_DM_TEST/utils/server`
 
    
@@ -825,18 +825,18 @@ function download_dataobject_async {
     fi
 
 
-    FILE_NAME=$(basename $OBJECT_PATH)
+    ITEM_NAME=$(basename $ITEM_PATH)
     TEMP=input-temp.json.tmp
 
     #Update the globus endpoint
     update_uid "$TEMPLATE" "$TEMP"
 
     #Update the file name 
-    INPUT_JSON=$(cat "$TEMP" | sed "s/dxfilename/$FILE_NAME/")
+    INPUT_JSON=$(cat "$TEMP" | sed "s/dxfilename/$ITEM_NAME/")
     echo "$INPUT_JSON" > input.json.tmp
 
 
-    curl -H "Content-Type: application/json" -d @input.json.tmp -X POST ${SERVER}/dataObject/$OBJECT_PATH/download  --config $HPC_DM_TEST/utils/config  -H "Accept: application/json" -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 
+    curl -H "Content-Type: application/json" -d @input.json.tmp -X POST ${SERVER}/$ITEM_PATH/download  --config $HPC_DM_TEST/utils/config  -H "Accept: application/json" -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 
     check_connection $RESPONSE_HEADER
 
 }
@@ -911,6 +911,49 @@ function get_notifications {
 
     check_connection $RESPONSE_HEADER
 }
+
+#Get the delivered notifications for a user 
+#Parameters:
+#           [page] The page number for the notifications
+#           [totalcount] The page number for the notifications
+function get_delivered_notifications {
+    
+    USAGE="USAGE: get_delivered_notificationn <page> <totalcount>"
+
+    if [-z "$1" ]
+    then
+        echo "ERROR: missing the page parameter." >&2
+        echo "$USAGE" >&2
+        exit
+    fi
+
+    if [-z "$2" ]
+    then
+        echo "ERROR: missing the totalcount parameter." >&2
+        echo "$USAGE" >&2
+        exit
+    fi
+
+    PAGE="$1"
+    TOTAL_COUNT="$2"
+    if [ -z $RESPONSE_HEADER ] 
+    then
+        RESPONSE_HEADER=delivered-notifications-response-header.tmp
+    fi
+
+    if [ -z $RESPONSE_MSG ] 
+    then
+        RESPONSE_MSG=delivered-notifications-response-message.json.tmp
+    fi
+
+    USERID=`get_username $HPC_DM_TEST/utils/config`
+    SERVER=`cat $HPC_DM_TEST/utils/server`
+
+    echo "curl -G -X GET $SERVER/notification/deliveryReceipts?page=$PAGE&totalcount --config $HPC_DM_TEST/utils/config   -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status"
+
+    check_connection $RESPONSE_HEADER
+}
+
 
 
 
@@ -1029,6 +1072,40 @@ function query_by_metadata {
     #CONFIG=$HPC_DM_TEST/utils/config 
 
     curl -H "Content-Type: application/json" -d @"$QUERY" -X POST $SERVER/$TYPE/query $CONFIG  -H "Accept: application/json" -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 
+
+    check_connection $RESPONSE_HEADER
+}
+
+
+
+# query a collection or an object by save query 
+# Arguments :<type> Either collection or dataObject
+#           :<query-name> 
+function query_by_saved_name {
+    if [ -z "$1" ] || [ -z "$2" ]
+    then 
+        echo "ERROR: using query_by_saved_name"
+        echo "USAGE: query_by_saved_name <type> <query-name>"     
+        exit
+    fi
+
+    TYPE="$1"
+    QUERY="$2"
+
+    CONFIG="--config $HPC_DM_TEST/utils/config"
+        
+    if [ "$TYPE" != "collection" ] && [ "$TYPE" != "dataObject" ]
+    then
+        echo "ERROR: type shoube be either collection or dataObject"
+        exit
+    fi
+
+    RESPONSE_HEADER=query-response-header.tmp
+    RESPONSE_MSG=query-response-msg.json.tmp
+
+    SERVER=`cat $HPC_DM_TEST/utils/server`
+
+    curl -X GET $SERVER/$TYPE/query/$QUERY $CONFIG  -H "Accept: application/json" -D $RESPONSE_HEADER -o $RESPONSE_MSG -s 2> curl-status 
 
     check_connection $RESPONSE_HEADER
 }
