Changed the verify globus mechanism and added asynchronous taskID check

diff --git a/src/hpc-server/hpc-ws-rs-test/src/test/dice/test-download-data-file/test-success-collection-download/runme b/src/hpc-server/hpc-ws-rs-test/src/test/dice/test-download-data-file/test-success-collection-download/runme
--- a/src/hpc-server/hpc-ws-rs-test/src/test/dice/test-download-data-file/test-success-collection-download/runme
+++ b/src/hpc-server/hpc-ws-rs-test/src/test/dice/test-download-data-file/test-success-collection-download/runme
@@ -26,16 +26,60 @@ RESPONSE_HEADER=download-response-header.tmp
 RESPONSE_MSG=download-response-message.json.tmp
 download_async "$FOLDER_PATH"
 
-HTTP_CODE=`get_http_code $RESPONSE_HEADER`
-echo $HTTP_CODE
 
-#Do not check the file is the code is not 200
+
+HTTP_CODE=`get_http_code $RESPONSE_HEADER`
+echo "download-request $HTTP_CODE"
+
+#Do not check the file if the code is not 200
 if [ $HTTP_CODE != 200 ] 
 then
     exit
 fi
 
+
+#Make sure a task ID is returned
+taskId=$(get_json_unquotted_value $RESPONSE_MSG taskId)
+if [[ -z "$taskId" ]] 
+then
+  echo "Can not find taskID in $RESPONSE_MSG" >&2;
+  exit 1
+fi
+
+
+#Get the status of the download request and verify it is true
+get_download_status "$taskId" collection 
+HTTP_CODE=`get_http_code $RESPONSE_HEADER`
+echo "get_status_code $HTTP_CODE"
+
+#Do not check the file is the code is not 200
+if [ $HTTP_CODE != 200 ] 
+then
+    echo "Unable to get download status" >&2
+    exit 1
+fi
+
+#Verify that the download is marked complete on the download status
+RESPONSE_HEADER=get-download-status-response-header.tmp
+RESPONSE_MSG=get-download-status-response-message.json.tmp
+status=$(get_json_unquotted_value $RESPONSE_MSG inProgress)
+echo "in_progress:$status"
+mv $RESPONSE_HEADER first-get-status-header.tmp
+mv $RESPONSE_MSG first-get-status-message.tmp
+
+
 FOLDER_PATH=$(get_json_value input.json.tmp fileId)
 verify_globus_file  $FOLDER_PATH
 FILE_ID=$(basename $(cat registered-dataobject-path.tmp))
 verify_globus_file  $FOLDER_PATH/$FILE_ID
+
+
+#Sleep 30s and verify the status is updated
+sleep 30
+get_download_status "$taskId" dataObject
+#Verify that the download is marked complete on the download status
+RESPONSE_HEADER=get-download-status-response-header.tmp
+RESPONSE_MSG=get-download-status-response-message.json.tmp
+status=$(get_json_unquotted_value $RESPONSE_MSG inProgress)
+echo "in_progress:$status"
+
