SVN-Revision: 1330

diff --git a/src/hpc/hpc-server/hpc-ws-rs-api/test/test-register/test-collection-registration/test-register-dataset-empty-path/runme b/src/hpc/hpc-server/hpc-ws-rs-api/test/test-register/test-collection-registration/test-register-dataset-empty-path/runme
--- a/src/hpc/hpc-server/hpc-ws-rs-api/test/test-register/test-collection-registration/test-register-dataset-empty-path/runme
+++ b/src/hpc/hpc-server/hpc-ws-rs-api/test/test-register/test-collection-registration/test-register-dataset-empty-path/runme
@@ -41,4 +41,4 @@ ERROR_MSG=`get_json_value $RESPONSE_MSG message`
 
 echo  "$RETURN_CODE"  1>&2
 echo  "$ERROR_TYPE"  1>&2
-echo "$ERROR_MSG"
+echo "$ERROR_MSG" 1>&2
