Added a check for unexpected http code
SVN-Revision: 1723

diff --git a/src/hpc/hpc-server/hpc-ws-rs-api/test/test-disable-authentication/test-search/test-search-collection/test-not-equal/runme b/src/hpc/hpc-server/hpc-ws-rs-api/test/test-disable-authentication/test-search/test-search-collection/test-not-equal/runme
--- a/src/hpc/hpc-server/hpc-ws-rs-api/test/test-disable-authentication/test-search/test-search-collection/test-not-equal/runme
+++ b/src/hpc/hpc-server/hpc-ws-rs-api/test/test-disable-authentication/test-search/test-search-collection/test-not-equal/runme
@@ -33,4 +33,7 @@ then
 elif [ "$HTTP_CODE" -ne "204" ]
 then 
         echo "ERROR: Got HTTP_CODE:$HTTP_CODE"  1>&2
+else
+then
+    echo "ERROR: Got unexpected HTTP_CODE:$HTTP_CODE"  1>&2
 fi
