Added new utilities for dataobject registration

diff --git a/utils/functions b/utils/functions
--- a/utils/functions
+++ b/utils/functions
@@ -150,5 +150,49 @@ function dm_register_dataobject {
     verify_registration "$RESPONSE_HEADER" "$RESPONSE_MSG" "$DESTINATION_PATH"
 }
 
+#Sync a folder in the current file system with a logical path in the Archive
+#There is no metadata for folder and they will be automatically created.
+#The files metadata is the list of attributes/values pair that are returned by the 
+#function "get_json-file"
+#Inputs: <source-folder>    The source folder on the file system
+#        <destination-path> The destination logical path
+function dm_sync_folder  {
+
+    USAGE="USAGE: dm_sync_folder <source-folder> <destination-path>"
+
+    if [ -z "$1" ] || [ -z "$2" ] 
+    then
+        echo "ERROR: using dm_register_collection" >&2
+        echo "Received: $@" >&2
+        echo "$USAGE" >&2
+        return
+    fi
+
+
+    RESPONSE_HEADER=dataObject-registration-response-header.tmp
+    RESPONSE_MSG=dataObject-registration-response-message.json.tmp
+
+
+    FILE_LIST="./test.txt /TEST_Archive/test.txt"
+
+    while read -r  NEW_FILE 
+    do 
+
+      SRC_PATH=$(echo $NEW_FILE | cut -d' ' -f1)
+      DST_PATH=$(echo $NEW_FILE | cut -d' ' -f2)
+
+      FILE_ATTRIBUTES=$(get_file_attributes $SRC_PATH)      
+      DESC_JSON=$(get_json_description $FILE_ATTRIBUTES)
+      echo $DESC_JSON >  temp.json
+      echo "dm_register_dataobject  temp.json $DST_PATH $SRC_PATH"
+      echo "verify_registration  $REPONSE_HEADER $RESPONSE_MSG $DST_PATH"
+
+      rm $RESPONSE_HEADER 2>/dev/null
+      rm $RESPONSE_MSG 2>/dev/null
+
+    done <<< "$FILE_LIST"
+
+}
+
 
 
diff --git a/utils/utilities b/utils/utilities
--- a/utils/utilities
+++ b/utils/utilities
@@ -145,5 +145,95 @@ function verify_registration {
 }
 
 
+#Get the json description of a file with automatic collection creation  
+#Inputs:  <json-attributes> : A string with the json attributes 
+function get_json_description {
+
+
+    USAGE="USAGE: get_json_description <json-attributes>"
+
+    if [ -z "$1" ] 
+    then
+        echo "ERROR: using get_json_description" >&2
+        echo "Received: $@" >&2
+        echo "$USAGE" >&2
+        return
+    fi
+
+    ATTRIBUTES="$1"
+    ALL_ATTRIBUTES="{ \"metadataEntries\": [ $ATTRIBUTES ], \"createParentCollections\": true, \"parentCollectionMetadataEntries\": [ { \"collection_type\", \"value\": \"Folder\" } ] }"
+
+    echo "$ALL_ATTRIBUTES"
+}
+
+#Get the metadata for a file
+#Inputs:  <file> : The file path 
+function get_file_attributes {
+
+    USAGE="USAGE: get_file_attributes <file>"
+
+    if [ -z "$1" ] 
+    then
+        echo "ERROR: using get_file_attributes" >&2
+        echo "Received: $@" >&2
+        echo "$USAGE" >&2
+        return
+    fi
+ 
+    FILE_PATH="$1"
+
+    FILE_NAME=$(basename $FILE_PATH)
+
+    echo "{\"attribute\":\"basename\",\"value\":\"$FILE_NAME\"}"
+}
+
+
+# list all files in a source main directory as well as sub- directories
+#Inputs: <source directory>  The directory to be synced with the Archive
+function list_new_files {
+
+    USAGE="USAGE: list_new_files <src-directory>"
+
+    if [ -z "$1" ] 
+    then
+        echo "ERROR: using list_new_files" >&2
+        echo "Received: $@" >&2
+        echo "$USAGE" >&2
+        return
+    fi
+ 
+
+
+    SOURCEDIR="$1"
+    
+    # keep track list of the old files .
+    #GZ: How does that keep track of different source directories?
+    LAST=/tmp/last.log
+    
+    # keep track the list of the current files .
+    CURRENT=/tmp/current.log
+    
+    # first time we create the log file
+    touch $LAST
+    
+    find $SOURCEDIR -type f > $CURRENT
+    
+    diff $LAST $CURRENT > /dev/null 2>&1
+    
+    # If there is no difference exit
+    if [ $? -eq 0 ]
+    then
+        echo "No changes"
+    else
+         echo "List of new files"
+        #diff $LAST $CURRENT | grep '^>'
+        diff last current | grep '^>' |awk '{print $2}' > /tmp/list_of_new_files.log
+    
+        # Lastly, move CURRENT to LAST
+        mv $CURRENT $LAST
+    fi
+}
+    
+
 
 
