Added a check for unexpected http code
SVN-Revision: 1722

diff --git a/src/hpc/hpc-server/hpc-ws-rs-api/test/test-disable-authentication/test-search/test-search-dataObjects/test-not-equal/runme b/src/hpc/hpc-server/hpc-ws-rs-api/test/test-disable-authentication/test-search/test-search-dataObjects/test-not-equal/runme
--- a/src/hpc/hpc-server/hpc-ws-rs-api/test/test-disable-authentication/test-search/test-search-dataObjects/test-not-equal/runme
+++ b/src/hpc/hpc-server/hpc-ws-rs-api/test/test-disable-authentication/test-search/test-search-dataObjects/test-not-equal/runme
@@ -22,9 +22,15 @@ search_by_metadata dataObject input.json dice_user
 
 HTTP_CODE=`get_http_code $RESPONSE_HEADER`
 
+
 ATTRIBUTE="\"name\""
 VALUE="dice test data file 2"
 
+if [ ! "$HTTP_CODE" -eq "200" ] && [ ! "$HTTP_CODE" -eq "200" ] 
+then
+    echo "ERROR: Got unexpeced HTTP code: $HTTP_CODE" >&2
+    exit
+fi
 
 if [ ! "$HTTP_CODE" -eq "204" ]
 then
